module.exports = {
    Attach: require('./Attach'),
    Climbable: require('./Climbable'),
    Climber: require('./Climber'),
    ContactDamage: require('./ContactDamage'),
    DeathSpawn: require('./DeathSpawn'),
    DeathZone: require('./DeathZone'),
    Disappearing: require('./Disappearing'),
    Environment: require('./Environment'),
    FixedForce: require('./FixedForce'),
    Glow: require('./Glow'),
    Health: require('./Health'),
    Invincibility: require('./Invincibility'),
    Jump: require('./Jump'),
    Lifetime: require('./Lifetime'),
    Light: require('./Light'),
    LightControl: require('./LightControl'),
    Move: require('./Move'),
    Physics: require('./Physics'),
    Projectile: require('./Projectile'),
    Rotate: require('./Rotate'),
    Solid: require('./Solid'),
    Spawn: require('./Spawn'),
    Translate: require('./Translate'),
};
